; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for HMU play:
FAMISTUDIO_USE_FAMITRACKER_TEMPO = 1
;FAMISTUDIO_USE_VOLUME_TRACK = 1

.export _music_data_hmu_play:=music_data_hmu_play

music_data_hmu_play:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : New song
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_hmu_play
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env1,@env4,@env0 ; 00 : Snare
	.word @env7,@env1,@env2,@env5 ; 01 : Kick
	.word @env6,@env3,@env4,@env0 ; 02 : Synth

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$03,$c9,$00,$02
@env2:
	.byte $c1,$c2,$c3,$c1,$c3,$c2,$c1,$00,$06
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $80,$ff,$ff,$ff,$ff,$c0,$00,$05
@env6:
	.byte $07,$cd,$c8,$c7,$c8,$00,$02,$ca,$c0,$00,$08
@env7:
	.byte $09,$cf,$ce,$ca,$c8,$c6,$c5,$00,$06,$c4,$02,$c3,$c3,$c2,$c2,$c1,$05,$c0,$00,$11

@samples:

@song0ch0:
	.byte $46, $06
@song0ch0loop:
	.byte $8b, $7a, $84, $27, $00, $81, $7e, $27, $87, $00, $85, $7a, $2b, $00, $81, $7e, $2b, $87, $00, $85, $2b, $00, $81, $29
	.byte $00, $81, $27, $00, $24, $85, $00, $8f, $29, $83, $00, $81, $29, $00, $83, $29, $83, $2e, $00, $87, $29, $81, $2b, $81
	.byte $00, $81, $27, $85, $00, $81, $27, $83, $00, $83, $27, $83, $00, $81, $27, $00, $83, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $84, $40, $04, $83, $03, $81, $00, $8b, $40, $04, $83, $07, $81, $00, $8b, $07, $00, $07, $00, $83, $07, $83, $05, $81
	.byte $00, $83, $40, $0c, $85, $00, $83, $04, $89, $05, $00, $85, $05, $00, $83, $05, $83, $0a, $00, $87, $05, $81, $07, $81
	.byte $00, $81, $03, $85, $00, $81, $03, $83, $00, $83, $03, $83, $00, $81, $03, $00, $83, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $85, $77, $84
@song0ref145:
	.byte $1b, $00, $81, $79, $1b
@song0ref150:
	.byte $00, $81, $77, $1b, $00, $81, $79, $1b
@song0ref158:
	.byte $00, $81, $77, $1f, $00, $81, $79, $1f, $00, $81, $77, $1f, $00, $81, $79, $1f
	.byte $41, $08
	.word @song0ref158
	.byte $77, $1d, $00, $81, $79, $1b, $00, $81, $77, $18, $00, $81, $79, $18, $00, $81, $77, $18, $00, $81, $79, $18, $00, $81
	.byte $77, $1d, $00, $81, $79, $1d, $00, $81, $77, $1d, $00, $81, $79, $1d, $00, $81, $77, $22, $00, $81, $79, $20, $00, $81
	.byte $77, $1d, $00, $81, $79, $1f
	.byte $41, $08
	.word @song0ref150
	.byte $77
	.byte $41, $0c
	.word @song0ref145
	.byte $77, $1b, $00, $81, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref246:
	.byte $79, $80, $1d, $83, $78, $82, $14, $00, $81, $79, $80, $1d, $83, $78, $82, $15, $00, $81
	.byte $41, $0a
	.word @song0ref246
	.byte $41, $0a
	.word @song0ref246
	.byte $41, $0a
	.word @song0ref246
	.byte $41, $0a
	.word @song0ref246
	.byte $41, $0a
	.word @song0ref246
	.byte $41, $0a
	.word @song0ref246
	.byte $41, $0a
	.word @song0ref246
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $bf, $42
	.word @song0ch4loop
