; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @pal
	.word @pal
@pal:
	.word @sfx_pal_cursor
	.word @sfx_pal_select
	.word @sfx_pal_steps
	.word @sfx_pal_pickup
	.word @sfx_pal_putdown
	.word @sfx_pal_victory

@sfx_pal_cursor:
	.byte $87,$53,$88,$02,$89,$f0,$01,$87,$0a,$86,$8b,$01,$87,$c0,$88,$01
	.byte $86,$8f,$01,$00
@sfx_pal_select:
	.byte $87,$ce,$88,$00,$89,$f0,$01,$87,$8a,$86,$8b,$01,$87,$45,$86,$8f
	.byte $01,$00
@sfx_pal_steps:
	.byte $87,$75,$88,$01,$89,$f0,$01,$87,$4e,$86,$8b,$01,$87,$25,$86,$8f
	.byte $01,$87,$01,$01,$87,$e1,$88,$00,$01,$00
@sfx_pal_pickup:
	.byte $84,$8c,$85,$00,$87,$bd,$88,$01,$86,$8f,$89,$f0,$01,$84,$83,$83
	.byte $bb,$86,$8c,$01,$84,$79,$83,$3f,$86,$88,$01,$84,$73,$86,$80,$01
	.byte $84,$71,$83,$bf,$01,$83,$30,$02,$83,$b0,$87,$9b,$88,$02,$86,$8f
	.byte $01,$83,$30,$86,$8c,$01,$86,$88,$01,$83,$b0,$00
@sfx_pal_putdown:
	.byte $84,$a9,$85,$00,$89,$f0,$01,$84,$a0,$83,$bb,$01,$84,$96,$83,$3f
	.byte $01,$84,$90,$01,$84,$8e,$83,$bf,$01,$83,$30,$01,$8a,$8f,$89,$3f
	.byte $01,$83,$b0,$89,$3c,$01,$83,$30,$89,$38,$01,$89,$30,$01,$83,$b0
	.byte $89,$3f,$01,$83,$30,$89,$3e,$01,$89,$3d,$01,$83,$b0,$89,$3c,$01
	.byte $83,$30,$89,$3b,$01,$89,$3a,$01,$83,$b0,$89,$39,$01,$83,$30,$89
	.byte $38,$01,$89,$37,$01,$83,$b0,$00
@sfx_pal_victory:
	.byte $89,$f0,$00

.export sounds
