; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for TestSongs:

.export _music_data_testsongs:=music_data_testsongs

music_data_testsongs:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Song 2
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_testsongs
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $25, $91, $26, $91, $27, $91, $28, $91, $29, $91, $2a
	.byte $91, $2b, $91, $2c, $91, $2d, $91, $2e, $91, $2f, $91, $30, $91, $31, $cd, $48, $00, $ff, $ff, $bd
@song0ref37:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref37
	.byte $41, $0c
	.word @song0ref37
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch4:
@song0ch3:
@song0ch2:
@song0ch1:
@song0ch1loop:
@song0ref74:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref74
	.byte $41, $0c
	.word @song0ref74
	.byte $41, $0c
	.word @song0ref74
	.byte $42
	.word @song0ch1loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $31, $91, $30, $91, $2f, $91, $2e, $91, $2d, $91, $2c
	.byte $91, $2b, $91, $2a, $91, $29, $91, $28, $91, $27, $91, $26, $91, $25, $cd, $48, $00, $ff, $ff, $bd
@song1ref37:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
	.byte $41, $0c
	.word @song1ref37
	.byte $41, $0c
	.word @song1ref37
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $42
	.word @song1ch0loop
@song1ch4:
@song1ch3:
@song1ch2:
@song1ch1:
@song1ch1loop:
@song1ref74:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song1ref74
	.byte $41, $0c
	.word @song1ref74
	.byte $41, $0c
	.word @song1ref74
	.byte $42
	.word @song1ch1loop
